title: Blogginest Blog ever Blogged
author: winter420-k
email: wint1guy@wintgin.net 
description: > # this means to ignore newlines until "baseurl:"
Super blogging bloggers of bloggityville

# social link

github_username:  wintoffer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
